import type { SiteConfig } from '@/shared/types';

export const siteConfigs: SiteConfig[] = [
  {
    domain: 'zara.com',
    name: 'ZARA',
    selectors: {
      productContainer: '.product-detail-view',
      productName: '.product-detail-info__header-name',
      productPrice: '.price__amount',
      productImages: '.media-image img',
      sizeSelector: '.size-selector__size-list',
      sizeChart: '.size-guide-content',
    },
    urlPattern: '/product/',
    tryOnButtonTarget: '.product-detail-actions__action-container',
  },
  {
    domain: 'hm.com',
    name: 'H&M',
    selectors: {
      productContainer: '.product-detail',
      productName: '.product-item-headline',
      productPrice: '.price-value',
      productImages: '.product-detail-main-image img',
      sizeSelector: '.size-selector',
      sizeChart: null,
    },
    urlPattern: '/productpage\\.',
    tryOnButtonTarget: '.product-detail-buy-section',
  },
  {
    domain: 'asos.com',
    name: 'ASOS',
    selectors: {
      productContainer: '#product-details',
      productName: '[data-test-id="product-title"]',
      productPrice: '[data-testid="current-price"]',
      productImages: '[data-testid="product-image"] img',
      sizeSelector: '[data-testid="size-selector"]',
      sizeChart: null,
    },
    urlPattern: '/prd/',
    tryOnButtonTarget: '[data-testid="product-actions"]',
  },
  {
    domain: 'uniqlo.com',
    name: 'UNIQLO',
    selectors: {
      productContainer: '.pdp-main',
      productName: '.pdp-product-name',
      productPrice: '.pdp-product-price',
      productImages: '.pdp-carousel img',
      sizeSelector: '.pdp-size-selector',
      sizeChart: null,
    },
    urlPattern: '/products/',
    tryOnButtonTarget: '.pdp-add-to-cart',
  },
  {
    domain: 'amazon.com',
    name: 'Amazon',
    selectors: {
      productContainer: '#dp-container',
      productName: '#productTitle',
      productPrice: '.a-price .a-offscreen',
      productImages: '#landingImage, #imgTagWrapperId img',
      sizeSelector: '#native_dropdown_selected_size_name, #variation_size_name',
      sizeChart: null,
    },
    urlPattern: '/dp/',
    tryOnButtonTarget: '#add-to-cart-button',
  },
  {
    domain: 'nordstrom.com',
    name: 'Nordstrom',
    selectors: {
      productContainer: '[data-element="main"]',
      productName: '[data-element="product-title"]',
      productPrice: '[data-element="price"]',
      productImages: '[data-element="product-media"] img',
      sizeSelector: '[data-element="size-selector"]',
      sizeChart: null,
    },
    urlPattern: '/s/',
    tryOnButtonTarget: '[data-element="add-to-bag"]',
  },
  {
    domain: 'gap.com',
    name: 'GAP',
    selectors: {
      productContainer: '.product-details',
      productName: '.product-title',
      productPrice: '.product-price',
      productImages: '.product-images img',
      sizeSelector: '.size-selector',
      sizeChart: null,
    },
    urlPattern: '/browse/product',
    tryOnButtonTarget: '.add-to-bag-btn',
  },
  {
    domain: 'mango.com',
    name: 'Mango',
    selectors: {
      productContainer: '.product-detail',
      productName: '.product-name',
      productPrice: '.product-sale-price, .product-price',
      productImages: '.product-images img',
      sizeSelector: '.size-selector',
      sizeChart: null,
    },
    urlPattern: '/product/',
    tryOnButtonTarget: '.add-to-cart',
  },
];

